### PR TITLE
Feature/link to firestore

### LINKED ISSUE #19: :sparkles: Bind firebase backend

### PR DESCRIPTION
**Pull request by johannchopin**
## Description

🍻 Fix #19. Only 'trick' was to initialise firestore in a `onMount`.
@Lyokolux You will need to add all the `.env` variables needed for firebase authentication in vercel (that's missing for the build to succeed). The values are shown here: https://console.firebase.google.com/u/0/project/ux-typing-experiment/settings/general/web:MDBkNDA2OWItNWMzZS00MTE1LWJkMzItMDUyMWUxODNjZGQ2

## Checklist

- [x] I compare my branch with `develop`
- [x] All tests passed after running `yarn s-check && yarn lint`

### CODE REVIEW

**Comment by Lyokolux** [comment]
> ## Description
> 
> beers Fix #19. Only 'trick' was to initialise firestore in a `onMount`.

Good job here !

> @Lyokolux You will need to add all the `.env` variables needed for firebase authentication in vercel (that's missing for the build to succeed). The values are shown here: https://console.firebase.google.com/u/0/project/ux-typing-experiment/settings/general/web:MDBkNDA2OWItNWMzZS00MTE1LWJkMzItMDUyMWUxODNjZGQ2

✅ Added to vercel

**Comment by Lyokolux** [comment]
@johannchopin it does not build (on Vercel and on my machine) for now.

Running `yarn dev` returns the following errors:
```
11:38:42 [vite] Error when evaluating SSR module /node_modules/firebase/firestore/lite/dist/index.mjs:
ReferenceError: exports is not defined
```

**Review by Lyokolux — CHANGES_REQUESTED** [review]
@johannchopin it does not build (on Vercel and on my machine) for now.

Running `yarn dev` returns errors such as:
```
11:38:42 [vite] Error when evaluating SSR module /node_modules/firebase/firestore/lite/dist/index.mjs:
ReferenceError: exports is not defined
```
```
11:41:09 [vite] Error when evaluating SSR module /node_modules/@firebase/firestore/dist/lite/index.node.cjs.js?v=f01bacec:
ReferenceError: exports is not defined
```

**Comment by johannchopin** [comment]
@Lyokolux Please try with at least node `v14.17.0`

**Comment by Lyokolux** [comment]
It works finally with the proper credentials

**Pull request merged**
